# Generated by Django 5.1.2 on 2024-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.CharField(default='October 20 2024', max_length=50),
            preserve_default=False,
        ),
    ]
