# Generated by Django 4.2.12 on 2024-10-23 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='mods',
            field=models.ManyToManyField(blank=True, related_name='moderating_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hub',
            name='private_hub',
            field=models.BooleanField(default=False),
        ),
    ]
