# Generated by Django 4.2.15 on 2024-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_pending_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='bg',
            field=models.ImageField(blank=True, null=True, upload_to='hub_backgrounds/'),
        ),
    ]
