# Generated by Django 4.2.12 on 2024-12-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0008_remove_hub_tag_tagged_hubs_alter_post_tag_color'),
        ('hubs', '0003_hub_pending_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tagged_hubs', to='Tags.hub_tag'),
        ),
    ]
