# Generated by Django 4.2.15 on 2024-12-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0004_hub_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='hub_banners/'),
        ),
    ]
