# Generated by Django 4.2.15 on 2024-12-03 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0004_hub_tags'),
        ('hubs', '0005_hub_banner'),
    ]

    operations = [
    ]
