# Generated by Django 4.2.15 on 2024-11-23 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Private_Messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='messageContent',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='messageTimestamp',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='userID',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageID', models.AutoField(primary_key=True, serialize=False)),
                ('messageContent', models.TextField()),
                ('messageTimestamp', models.DateTimeField(auto_now_add=True)),
                ('conversationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Private_Messaging.conversation')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
