# Generated by Django 4.2.12 on 2024-10-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='downvotes',
            new_name='dislikePost',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvotes',
            new_name='likePost',
        ),
    ]
