# Generated by Django 4.2.15 on 2024-11-24 07:32

import Posts.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, scale=None, size=[1000, 1000], upload_to=Posts.models.get_upload_path),
        ),
    ]
