# Generated by Django 4.2.15 on 2024-11-18 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_post_hot_score'),
        ('Posts', '0005_post_last_edited'),
    ]

    operations = [
    ]
