# Generated by Django 4.2.15 on 2024-11-19 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
        ('Posts', '0006_merge_0005_post_hot_score_0005_post_last_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='Tags.tags'),
        ),
    ]
