# Generated by Django 4.2.15 on 2024-11-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0004_hub_tag_post_tag_remove_tag_hub_and_more'),
        ('Posts', '0007_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='Tags.post_tag'),
        ),
    ]
