# Generated by Django 4.2.12 on 2024-11-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0006_alter_post_tag_name'),
        ('Posts', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tagged_post', to='Tags.post_tag'),
        ),
    ]
