# Generated by Django 4.2.15 on 2024-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0003_hub_pending_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isGlobal', models.BooleanField(default=True)),
                ('hub', models.ManyToManyField(blank=True, related_name='hub', to='hubs.hub')),
            ],
        ),
    ]
