# Generated by Django 4.2.15 on 2024-11-22 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_pending_members'),
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tagged_hubs',
            field=models.ManyToManyField(blank=True, related_name='tag_for_global', to='hubs.hub'),
        ),
        migrations.RemoveField(
            model_name='tags',
            name='hub',
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AddField(
            model_name='tags',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_for_hub', to='hubs.hub'),
        ),
    ]
