# Generated by Django 4.2.15 on 2024-11-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_pending_members'),
        ('Posts', '0007_post_tag'),
        ('Tags', '0002_tags_tagged_hubs_remove_tags_hub_alter_tags_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
