# Generated by Django 4.2.15 on 2024-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0003_rename_tags_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tag',
            name='hub',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tagged_hubs',
        ),
    ]
