# Generated by Django 4.2.15 on 2024-11-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_hub_pending_members'),
        ('Tags', '0004_hub_tag_post_tag_remove_tag_hub_and_more'),
        ('Posts', '0008_alter_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='post_tag',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_tag', to='hubs.hub'),
        ),
        migrations.AddField(
            model_name='hub_tag',
            name='tagged_hubs',
            field=models.ManyToManyField(blank=True, related_name='hub_tag', to='hubs.hub'),
        ),
    ]
