# Generated by Django 4.2.12 on 2024-11-30 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0006_alter_post_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_tag',
            name='color',
            field=models.CharField(blank=True, default='cfbc0d', max_length=20),
        ),
    ]
