# Generated by Django 4.2.12 on 2024-12-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0008_remove_hub_tag_tagged_hubs_alter_post_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub_tag',
            name='color',
            field=models.CharField(blank=True, default='#cfbc0d', max_length=20),
        ),
    ]
