# Generated by Django 4.2.12 on 2024-10-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testhubs', '0003_rename_content_comment_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
