# Generated by Django 4.2.15 on 2024-11-22 08:44

import Profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=Profile.models.get_default_username, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='defaultpfp.png', upload_to=Profile.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
